# Generated by Django 4.1.4 on 2023-02-14 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modellapp', '0002_alter_student_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='test',
            field=models.BooleanField(default=True),
        ),
    ]
