# Generated by Django 4.1.4 on 2023-02-15 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modellapp', '0004_student_year_in_school'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('age', models.IntegerField()),
                ('city', models.CharField(max_length=15)),
            ],
        ),
    ]
