# Generated by Django 4.1.4 on 2023-02-16 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('electronics', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mobile',
            new_name='MobileModel',
        ),
    ]
