# Generated by Django 4.1.4 on 2023-02-16 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electronics', '0002_rename_mobile_mobilemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobilemodel',
            name='colours',
            field=models.CharField(choices=[('BLACK', 'Black'), ('RED', 'Red'), ('SILVER', 'Silver')], default='BLACK', max_length=6),
        ),
    ]
