# Generated by Django 4.1.4 on 2023-03-08 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseInfoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=25)),
                ('cduration', models.FloatField()),
                ('cfees', models.IntegerField()),
                ('cmentor', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='StudRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=25)),
                ('smobile', models.IntegerField()),
                ('semail', models.EmailField(max_length=254)),
                ('saddress', models.TextField()),
            ],
        ),
    ]
