# Generated by Django 4.1.4 on 2023-04-11 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stud_id', models.IntegerField(max_length=100)),
                ('sname', models.CharField(max_length=100)),
                ('stud_email', models.EmailField(max_length=100)),
                ('stud_pass', models.CharField(max_length=100)),
            ],
        ),
    ]
