# Generated by Django 4.1.4 on 2023-12-21 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountsDetails',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('account_name', models.CharField(max_length=25)),
                ('bal', models.FloatField()),
                ('acdate', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=13)),
            ],
        ),
    ]
