# Generated by Django 4.1.4 on 2023-02-22 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShirtModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('size', models.CharField(max_length=15)),
                ('img', models.ImageField(upload_to='xyz')),
            ],
        ),
    ]
